name: amplify_db_common_example
description: Demonstrates how to use the amplify_db_common plugin.
publish_to: "none"

environment:
  flutter: ">=3.3.0"
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  amplify_db_common: ">=0.1.2+5 <0.2.0"
  drift: ">=2.4.0 <2.7.0"
  flutter:
    sdk: flutter

# Needed to support both Flutter 3.3 + 3.7 in CI.
# TODO(dnys1): Remove when Flutter 3.3 is no longer supported
dependency_overrides:
  async: ^2.9.0

dev_dependencies:
  amplify_lints: ^2.0.0
  drift_dev: ^2.2.0+1
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  plugin:
    # We use the same class names as sqlite3_flutter_libs since users should never depend on both packages at the same
    # time, not even transitively.
    platforms:
      android:
        package: eu.simonbinder.sqlite3_flutter_libs
        pluginClass: Sqlite3FlutterLibsPlugin
      ios:
        pluginClass: Sqlite3FlutterLibsPlugin
